export const accommodationsData = [
  {
    city: 'Hunter',
    name: 'The Hunter Inn',
    state: 'NY',
    street: '7433 Main Street',
    phoneNumber: '5182633777',
    websiteAddress: 'http://www.hunterinn.com/',
    zip: '12442',
  },
];
export const otherAccommodationsData = [
  {
    city: 'Roxbury',
    name: 'Queens Mountain Inn',
    state: 'NY',
    street: '53470 State Highway 30',
    phoneNumber: '9173048053',
    websiteAddress: 'http://queensmtninn.com/',
    zip: '12474',
  },
  {
    city: 'Roxbury',
    name: 'Roxbury Manor',
    state: 'NY',
    street: ' 53642 State Highway 30',
    phoneNumber: '5163174573',
    websiteAddress: 'https://www.roxburyrocks.com/',
    zip: '12474',
  },
  {
    city: 'Roxbury',
    name: 'The Roxbury Motel',
    state: 'NY',
    street: '2258 County Highway 41',
    phoneNumber: '6073267200',
    websiteAddress: 'http://theroxburymotel.com/',
    zip: '12474',
  },
  {
    city: 'Roxbury',
    name: 'Scudder Hill House',
    state: 'NY',
    street: '24 County Highway 8',
    phoneNumber: '6073267310',
    websiteAddress: 'https://www.scudderhillhouse.com',
    zip: '12474',
  },
  {
    city: 'Roxbury',
    name: 'Stylish Catskill Cabin',
    state: 'NY',
    street: '50 Maple Lane',
    phoneNumber: '8009139813',
    websiteAddress: 'https://www.greenlabelhome.com/roxbury-contemporary.html',
    zip: '12474',
  },
];
